# Generated by Django 5.0.1 on 2024-02-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
